"""WeBrick color palette for mosaic color matching.

Source of the WeBrick IDs and cross-references:
https://www.webrick.com/color-chart

Important:
- WeBrick IDs, LEGO IDs, Rebrickable IDs and BrickLink IDs are kept separate.
- RGB values are LDraw rendering values where a reliable LDraw correspondence is known.
- RGB=None means there is no sufficiently reliable LDraw RGB mapping here; do not invent a value.
- WEBRICK_COLOR_CHART contains the complete current WeBrick Color Guide listed on the source page.
- WEBRICK_MOSAIC_PALETTE contains only colors with verified RGB values, because the mosaic matcher requires RGB tuples.
"""

WEBRICK_COLOR_CHART = [
    {
        "webrick_id": 1,
        "name": 'White',
        "de": 'Weiß',
        "lego_id": 1,
        "rebrickable_id": 15,
        "bricklink_id": 1,
        "ldraw_id": 15,
        "rgb_hex": 'FFFFFF',
    },
    {
        "webrick_id": 3,
        "name": 'Light Yellow',
        "de": 'Hellgelb',
        "lego_id": 3,
        "rebrickable_id": 18,
        "bricklink_id": 33,
        "ldraw_id": 18,
        "rgb_hex": 'FBE696',
    },
    {
        "webrick_id": 5,
        "name": 'Tan',
        "de": 'Tan / Beige',
        "lego_id": 5,
        "rebrickable_id": 19,
        "bricklink_id": 2,
        "ldraw_id": 19,
        "rgb_hex": 'E4CD9E',
    },
    {
        "webrick_id": 18,
        "name": 'Nougat',
        "de": 'Nougat',
        "lego_id": 18,
        "rebrickable_id": 92,
        "bricklink_id": 28,
        "ldraw_id": 92,
        "rgb_hex": 'D09168',
    },
    {
        "webrick_id": 21,
        "name": 'Red',
        "de": 'Rot',
        "lego_id": 21,
        "rebrickable_id": 4,
        "bricklink_id": 5,
        "ldraw_id": 4,
        "rgb_hex": 'B40000',
    },
    {
        "webrick_id": 23,
        "name": 'Blue',
        "de": 'Blau',
        "lego_id": 23,
        "rebrickable_id": 1,
        "bricklink_id": 7,
        "ldraw_id": 1,
        "rgb_hex": '1E5AA8',
    },
    {
        "webrick_id": 24,
        "name": 'Yellow',
        "de": 'Gelb',
        "lego_id": 24,
        "rebrickable_id": 14,
        "bricklink_id": 3,
        "ldraw_id": 14,
        "rgb_hex": 'FAC80A',
    },
    {
        "webrick_id": 26,
        "name": 'Black',
        "de": 'Schwarz',
        "lego_id": 26,
        "rebrickable_id": 0,
        "bricklink_id": 11,
        "ldraw_id": 0,
        "rgb_hex": '1B2A34',
    },
    {
        "webrick_id": 28,
        "name": 'Green',
        "de": 'Dunkelgrün',
        "lego_id": 28,
        "rebrickable_id": 2,
        "bricklink_id": 6,
        "ldraw_id": 2,
        "rgb_hex": '00852B',
    },
    {
        "webrick_id": 37,
        "name": 'Bright Green',
        "de": 'Grün',
        "lego_id": 37,
        "rebrickable_id": 10,
        "bricklink_id": 36,
        "ldraw_id": 10,
        "rgb_hex": '58AB41',
    },
    {
        "webrick_id": 38,
        "name": 'Dark Orange',
        "de": 'Dunkelorange',
        "lego_id": 38,
        "rebrickable_id": 484,
        "bricklink_id": 68,
        "ldraw_id": 484,
        "rgb_hex": '91501C',
    },
    {
        "webrick_id": 40,
        "name": 'Trans-Clear',
        "de": 'Transparent / Klar',
        "lego_id": 40,
        "rebrickable_id": 47,
        "bricklink_id": 12,
        "ldraw_id": 47,
        "rgb_hex": 'FCFCFC',
    },
    {
        "webrick_id": 41,
        "name": 'Trans-Red',
        "de": 'Transparent Rot',
        "lego_id": 41,
        "rebrickable_id": 36,
        "bricklink_id": 17,
        "ldraw_id": 36,
        "rgb_hex": 'C91A09',
    },
    {
        "webrick_id": 42,
        "name": 'Trans-Light Blue',
        "de": 'Transparent Hellblau',
        "lego_id": 42,
        "rebrickable_id": 41,
        "bricklink_id": 15,
        "ldraw_id": 43,
        "rgb_hex": 'AEE9EF',
    },
    {
        "webrick_id": 43,
        "name": 'Trans-Dark Blue',
        "de": 'Transparent Dunkelblau',
        "lego_id": 43,
        "rebrickable_id": 33,
        "bricklink_id": 14,
        "ldraw_id": 33,
        "rgb_hex": '0020A0',
    },
    {
        "webrick_id": 44,
        "name": 'Trans-Yellow',
        "de": 'Transparent Gelb',
        "lego_id": 44,
        "rebrickable_id": 46,
        "bricklink_id": 19,
        "ldraw_id": 46,
        "rgb_hex": 'F5CD2F',
    },
    {
        "webrick_id": 48,
        "name": 'Trans-Green',
        "de": 'Transparent Grün',
        "lego_id": 48,
        "rebrickable_id": 34,
        "bricklink_id": 20,
        "ldraw_id": 34,
        "rgb_hex": '237841',
    },
    {
        "webrick_id": 49,
        "name": 'Trans Neon Green',
        "de": 'Transparent Neongrün',
        "lego_id": 49,
        "rebrickable_id": 42,
        "bricklink_id": 16,
        "ldraw_id": 42,
        "rgb_hex": 'C0FF00',
    },
    {
        "webrick_id": 102,
        "name": 'Medium Blue',
        "de": 'Mittelblau',
        "lego_id": 102,
        "rebrickable_id": 73,
        "bricklink_id": 42,
        "ldraw_id": 73,
        "rgb_hex": '7396C8',
    },
    {
        "webrick_id": 106,
        "name": 'Orange',
        "de": 'Orange',
        "lego_id": 106,
        "rebrickable_id": 25,
        "bricklink_id": 4,
        "ldraw_id": 25,
        "rgb_hex": 'D67923',
    },
    {
        "webrick_id": 107,
        "name": 'Dark Turquoise',
        "de": 'Dunkeltürkis',
        "lego_id": 107,
        "rebrickable_id": 3,
        "bricklink_id": 39,
        "ldraw_id": 3,
        "rgb_hex": '069D9F',
    },
    {
        "webrick_id": 111,
        "name": 'Trans-Black',
        "de": 'Transparent Schwarz',
        "lego_id": 111,
        "rebrickable_id": 40,
        "bricklink_id": 13,
        "ldraw_id": 40,
        "rgb_hex": '635F52',
    },
    {
        "webrick_id": 113,
        "name": 'Trans-Dark Pink',
        "de": 'Transparent Dunkelpink',
        "lego_id": 113,
        "rebrickable_id": 45,
        "bricklink_id": 50,
        "ldraw_id": 37,
        "rgb_hex": 'DF6695',
    },
    {
        "webrick_id": 119,
        "name": 'Lime',
        "de": 'Lime',
        "lego_id": 119,
        "rebrickable_id": 27,
        "bricklink_id": 34,
        "ldraw_id": 27,
        "rgb_hex": 'A5CA18',
    },
    {
        "webrick_id": 124,
        "name": 'Magenta',
        "de": 'Magenta',
        "lego_id": 124,
        "rebrickable_id": 26,
        "bricklink_id": 71,
        "ldraw_id": 26,
        "rgb_hex": '901F76',
    },
    {
        "webrick_id": 126,
        "name": 'Trans-Purple',
        "de": 'Transparent Lila',
        "lego_id": 126,
        "rebrickable_id": 52,
        "bricklink_id": 51,
        "ldraw_id": 52,
        "rgb_hex": 'A5A5CB',
    },
    {
        "webrick_id": 135,
        "name": 'Sand Blue',
        "de": 'Sandblau',
        "lego_id": 135,
        "rebrickable_id": 379,
        "bricklink_id": 55,
        "ldraw_id": 379,
        "rgb_hex": '70819A',
    },
    {
        "webrick_id": 138,
        "name": 'Dark Tan',
        "de": 'Dunkelbeige',
        "lego_id": 138,
        "rebrickable_id": 28,
        "bricklink_id": 69,
        "ldraw_id": 28,
        "rgb_hex": '897D62',
    },
    {
        "webrick_id": 140,
        "name": 'Dark Blue',
        "de": 'Dunkelblau',
        "lego_id": 140,
        "rebrickable_id": 272,
        "bricklink_id": 63,
        "ldraw_id": 272,
        "rgb_hex": '19325A',
    },
    {
        "webrick_id": 141,
        "name": 'Dark Green',
        "de": 'Dunkelgrün',
        "lego_id": 141,
        "rebrickable_id": 288,
        "bricklink_id": 80,
        "ldraw_id": 141,
        "rgb_hex": None,
    },
    {
        "webrick_id": 151,
        "name": 'Sand Green',
        "de": 'Sandgrün',
        "lego_id": 151,
        "rebrickable_id": 378,
        "bricklink_id": 48,
        "ldraw_id": 378,
        "rgb_hex": '708E7C',
    },
    {
        "webrick_id": 154,
        "name": 'Dark Red',
        "de": 'Dunkelrot',
        "lego_id": 154,
        "rebrickable_id": 320,
        "bricklink_id": 59,
        "ldraw_id": 320,
        "rgb_hex": None,
    },
    {
        "webrick_id": 182,
        "name": 'Trans-Orange',
        "de": 'Transparent Orange',
        "lego_id": 182,
        "rebrickable_id": 182,
        "bricklink_id": 98,
        "ldraw_id": 57,
        "rgb_hex": 'F08F1C',
    },
    {
        "webrick_id": 191,
        "name": 'Bright Light Orange',
        "de": 'Hellorange',
        "lego_id": 191,
        "rebrickable_id": 191,
        "bricklink_id": 110,
        "ldraw_id": 191,
        "rgb_hex": 'FCAC00',
    },
    {
        "webrick_id": 192,
        "name": 'Reddish Brown',
        "de": 'Rotbraun',
        "lego_id": 192,
        "rebrickable_id": 70,
        "bricklink_id": 88,
        "ldraw_id": 70,
        "rgb_hex": '5F3109',
    },
    {
        "webrick_id": 194,
        "name": 'Light Bluish Gray',
        "de": 'Hellblaugrau',
        "lego_id": 194,
        "rebrickable_id": 71,
        "bricklink_id": 86,
        "ldraw_id": 71,
        "rgb_hex": '969696',
    },
    {
        "webrick_id": 199,
        "name": 'Dark Bluish Gray',
        "de": 'Dunkelblaugrau',
        "lego_id": 199,
        "rebrickable_id": 72,
        "bricklink_id": 85,
        "ldraw_id": 72,
        "rgb_hex": '646464',
    },
    {
        "webrick_id": 212,
        "name": 'Bright Light Blue',
        "de": 'Helles Blau',
        "lego_id": 212,
        "rebrickable_id": 212,
        "bricklink_id": 105,
        "ldraw_id": 212,
        "rgb_hex": '9DC3F7',
    },
    {
        "webrick_id": 221,
        "name": 'Dark Pink',
        "de": 'Dunkelpink',
        "lego_id": 221,
        "rebrickable_id": 5,
        "bricklink_id": 47,
        "ldraw_id": 5,
        "rgb_hex": 'D3359D',
    },
    {
        "webrick_id": 222,
        "name": 'Bright Pink',
        "de": 'Pink',
        "lego_id": 222,
        "rebrickable_id": 29,
        "bricklink_id": 104,
        "ldraw_id": 29,
        "rgb_hex": 'FF9ECD',
    },
    {
        "webrick_id": 226,
        "name": 'Bright Light Yellow',
        "de": 'Hellgelb (Bright Light)',
        "lego_id": 226,
        "rebrickable_id": 226,
        "bricklink_id": 103,
        "ldraw_id": 226,
        "rgb_hex": 'FFEC6C',
    },
    {
        "webrick_id": 268,
        "name": 'Dark Purple',
        "de": 'Dunkellila',
        "lego_id": 268,
        "rebrickable_id": 85,
        "bricklink_id": 89,
        "ldraw_id": 85,
        "rgb_hex": '441A91',
    },
    {
        "webrick_id": 283,
        "name": 'Light Flesh',
        "de": 'Heller Hautton',
        "lego_id": 283,
        "rebrickable_id": 78,
        "bricklink_id": 90,
        "ldraw_id": 78,
        "rgb_hex": 'FFC995',
    },
    {
        "webrick_id": 294,
        "name": 'Glow In Dark Trans',
        "de": 'Leuchtend transparent',
        "lego_id": 294,
        "rebrickable_id": 294,
        "bricklink_id": 118,
        "ldraw_id": 294,
        "rgb_hex": 'BDC6AD',
    },
    {
        "webrick_id": 297,
        "name": 'Pearl Gold',
        "de": 'Perlgold',
        "lego_id": 297,
        "rebrickable_id": 297,
        "bricklink_id": 115,
        "ldraw_id": 297,
        "rgb_hex": 'CC9C2B',
    },
    {
        "webrick_id": 308,
        "name": 'Dark Brown',
        "de": 'Dunkelbraun',
        "lego_id": 308,
        "rebrickable_id": 308,
        "bricklink_id": 120,
        "ldraw_id": 308,
        "rgb_hex": None,
    },
    {
        "webrick_id": 309,
        "name": 'Plated Silver',
        "de": 'Versilbert / Chrome Silver',
        "lego_id": 309,
        "rebrickable_id": 383,
        "bricklink_id": 22,
        "ldraw_id": 383,
        "rgb_hex": None,
    },
    {
        "webrick_id": 310,
        "name": 'Plating gold',
        "de": 'Vergoldet / Chrome Gold',
        "lego_id": 310,
        "rebrickable_id": 334,
        "bricklink_id": 21,
        "ldraw_id": 334,
        "rgb_hex": None,
    },
    {
        "webrick_id": 311,
        "name": 'Trans-Bright Green',
        "de": 'Transparent Hellgrün',
        "lego_id": 311,
        "rebrickable_id": 35,
        "bricklink_id": 108,
        "ldraw_id": 35,
        "rgb_hex": '56E646',
    },
    {
        "webrick_id": 312,
        "name": 'Medium Dark Flesh',
        "de": 'Medium Dark Flesh / Medium Nougat',
        "lego_id": 312,
        "rebrickable_id": 84,
        "bricklink_id": 150,
        "ldraw_id": 84,
        "rgb_hex": 'CC702A',
    },
    {
        "webrick_id": 315,
        "name": 'Flat Silver',
        "de": 'Flachsilber',
        "lego_id": 315,
        "rebrickable_id": 179,
        "bricklink_id": 95,
        "ldraw_id": 179,
        "rgb_hex": '898788',
    },
    {
        "webrick_id": 316,
        "name": 'Titanium Metallic',
        "de": 'Titanium Metallic',
        "lego_id": 316,
        "rebrickable_id": 148,
        "bricklink_id": 77,
        "ldraw_id": 83,
        "rgb_hex": '1A2831',
    },
    {
        "webrick_id": 321,
        "name": 'Dark Azure',
        "de": 'Dunkel-Azur',
        "lego_id": 321,
        "rebrickable_id": 321,
        "bricklink_id": 153,
        "ldraw_id": 321,
        "rgb_hex": '1498D7',
    },
    {
        "webrick_id": 322,
        "name": 'Medium Azure',
        "de": 'Mittel-Azur',
        "lego_id": 322,
        "rebrickable_id": 322,
        "bricklink_id": 156,
        "ldraw_id": 322,
        "rgb_hex": '3EC2DD',
    },
    {
        "webrick_id": 323,
        "name": 'Light Aqua',
        "de": 'Hell-Aqua',
        "lego_id": 323,
        "rebrickable_id": 323,
        "bricklink_id": 152,
        "ldraw_id": 323,
        "rgb_hex": 'BDDCD8',
    },
    {
        "webrick_id": 324,
        "name": 'Medium Lavender',
        "de": 'Mittel-Lavendel',
        "lego_id": 324,
        "rebrickable_id": 324,
        "bricklink_id": 157,
        "ldraw_id": 324,
        "rgb_hex": 'A06EB9',
    },
    {
        "webrick_id": 325,
        "name": 'Lavender',
        "de": 'Lavendel',
        "lego_id": 325,
        "rebrickable_id": 325,
        "bricklink_id": 154,
        "ldraw_id": 325,
        "rgb_hex": 'CDA4DE',
    },
    {
        "webrick_id": 326,
        "name": 'Yellowish Green',
        "de": 'Gelbgrün',
        "lego_id": 326,
        "rebrickable_id": 158,
        "bricklink_id": 158,
        "ldraw_id": 326,
        "rgb_hex": 'DFEEA5',
    },
    {
        "webrick_id": 330,
        "name": 'Olive Green',
        "de": 'Olivgrün',
        "lego_id": 330,
        "rebrickable_id": 326,
        "bricklink_id": 155,
        "ldraw_id": 330,
        "rgb_hex": '9B9A5A',
    },
    {
        "webrick_id": 1017,
        "name": 'Coral',
        "de": 'Koralle',
        "lego_id": 1017,
        "rebrickable_id": 1050,
        "bricklink_id": 220,
        "ldraw_id": 353,
        "rgb_hex": 'FF6D77',
    },
    {
        "webrick_id": 999,
        "name": 'Army Green',
        "de": 'Armeegrün',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
    {
        "webrick_id": 17,
        "name": 'Orchid Pink',
        "de": 'Orchideenrosa',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
    {
        "webrick_id": 27,
        "name": 'Wheat',
        "de": 'Weizen',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
    {
        "webrick_id": 56,
        "name": 'Light Grayish blue',
        "de": 'Hellblaugrau (spezial)',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
    {
        "webrick_id": 64,
        "name": 'Languid Lavender',
        "de": 'Languid Lavender',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
    {
        "webrick_id": 92,
        "name": 'Greyish White',
        "de": 'Grauweiß',
        "lego_id": None,
        "rebrickable_id": None,
        "bricklink_id": None,
        "ldraw_id": None,
        "rgb_hex": None,
    },
]

# RGB-keyed palette used by the mosaic algorithm.
# Only entries with a verified RGB value are included.
WEBRICK_MOSAIC_PALETTE = {}

for color in WEBRICK_COLOR_CHART:
    if color["rgb_hex"] is None:
        continue
    h = color["rgb_hex"]
    rgb = tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
    WEBRICK_MOSAIC_PALETTE[rgb] = {
        "webrick_id": color["webrick_id"],
        "ldraw_id": color["ldraw_id"],
        "lego_id": color["lego_id"],
        "rebrickable_id": color["rebrickable_id"],
        "bricklink_id": color["bricklink_id"],
        "name": color["name"],
        "de": color["de"],
    }

# Quick lookup by WeBrick ID.
WEBRICK_BY_ID = {c["webrick_id"]: c for c in WEBRICK_COLOR_CHART}

# Expected number of colors in the current WeBrick Color Guide.
WEBRICK_COLOR_COUNT = len(WEBRICK_COLOR_CHART)
