WEBRICK_SOLID_PALETTE = {
    (27, 42, 52): {
        "bricklink_id": 0,
        "de": "Schwarz",
        "hex": "#1b2a34",
        "ldraw_id": 0,
        "lego_id": 11,
        "name": "Black",
        "rebrickable_id": 26,
        "webrick_id": 26,
    },
    (242, 243, 242): {
        "bricklink_id": 15,
        "de": "Weiß",
        "hex": "#f2f3f2",
        "ldraw_id": 15,
        "lego_id": 1,
        "name": "White",
        "rebrickable_id": 15,
        "webrick_id": 1,
    },
    (180, 0, 29): {
        "bricklink_id": 4,
        "de": "Rot",
        "hex": "#b4001d",
        "ldraw_id": 4,
        "lego_id": 5,
        "name": "Red",
        "rebrickable_id": 4,
        "webrick_id": 21,
    },
    (144, 31, 118): {
        "bricklink_id": 26,
        "de": "Magenta",
        "hex": "#901f76",
        "ldraw_id": 26,
        "lego_id": 71,
        "name": "Magenta",
        "rebrickable_id": 26,
        "webrick_id": 124,
    },
    (245, 205, 47): {
        "bricklink_id": 14,
        "de": "Gelb",
        "hex": "#f5cd2f",
        "ldraw_id": 14,
        "lego_id": 3,
        "name": "Yellow",
        "rebrickable_id": 14,
        "webrick_id": 24,
    },
    (0, 156, 68): {
        "bricklink_id": 2,
        "de": "Grün",
        "hex": "#009c44",
        "ldraw_id": 2,
        "lego_id": 6,
        "name": "Green",
        "rebrickable_id": 2,
        "webrick_id": 28,
    },
    (0, 76, 146): {
        "bricklink_id": 1,
        "de": "Blau",
        "hex": "#004c92",
        "ldraw_id": 1,
        "lego_id": 7,
        "name": "Blue",
        "rebrickable_id": 1,
        "webrick_id": 23,
    },
    (13, 105, 171): {
        "bricklink_id": 73,
        "de": "Mittelblau",
        "hex": "#0d69ab",
        "ldraw_id": 73,
        "lego_id": 42,
        "name": "Medium Blue",
        "rebrickable_id": 73,
        "webrick_id": 102,
    },
    (112, 121, 101): {
        "bricklink_id": 378,
        "de": "Sandgrün",
        "hex": "#707965",
        "ldraw_id": 378,
        "lego_id": 48,
        "name": "Sand Green",
        "rebrickable_id": 378,
        "webrick_id": 151,
    },
    (132, 124, 111): {
        "bricklink_id": 379,
        "de": "Sandblau",
        "hex": "#847c6f",
        "ldraw_id": 379,
        "lego_id": 55,
        "name": "Sand Blue",
        "rebrickable_id": 379,
        "webrick_id": 135,
    },
    (95, 49, 9): {
        "bricklink_id": 70,
        "de": "Rotbraun",
        "hex": "#5f3109",
        "ldraw_id": 70,
        "lego_id": 88,
        "name": "Reddish Brown",
        "rebrickable_id": 70,
        "webrick_id": 192,
    },
    (221, 196, 150): {
        "bricklink_id": 19,
        "de": "Tan / Beige",
        "hex": "#ddc496",
        "ldraw_id": 19,
        "lego_id": 2,
        "name": "Tan",
        "rebrickable_id": 19,
        "webrick_id": 5,
    },
    (178, 117, 89): {
        "bricklink_id": 28,
        "de": "Dunkelbeige",
        "hex": "#b27559",
        "ldraw_id": 28,
        "lego_id": 69,
        "name": "Dark Tan",
        "rebrickable_id": 28,
        "webrick_id": 138,
    },
    (246, 173, 151): {
        "bricklink_id": 78,
        "de": "Heller Hautton",
        "hex": "#f6ad97",
        "ldraw_id": 78,
        "lego_id": 90,
        "name": "Light Flesh",
        "rebrickable_id": 78,
        "webrick_id": 283,
    },
    (204, 112, 42): {
        "bricklink_id": 84,
        "de": "Medium Dark Flesh / Medium Nougat",
        "hex": "#cc702a",
        "ldraw_id": 84,
        "lego_id": 150,
        "name": "Medium Dark Flesh",
        "rebrickable_id": 84,
        "webrick_id": 312,
    },
    (110, 22, 25): {
        "bricklink_id": 25,
        "de": "Dunkelrot",
        "hex": "#6e1619",
        "ldraw_id": 25,
        "lego_id": 85,
        "name": "Dark Red",
        "rebrickable_id": 25,
        "webrick_id": 320,
    },
    (16, 33, 65): {
        "bricklink_id": 272,
        "de": "Dunkelblau",
        "hex": "#102141",
        "ldraw_id": 272,
        "lego_id": 63,
        "name": "Dark Blue",
        "rebrickable_id": 272,
        "webrick_id": 272,
    },
    (0, 78, 41): {
        "bricklink_id": 37,
        "de": "Dunkelgrün",
        "hex": "#004e29",
        "ldraw_id": 37,
        "lego_id": 28,
        "name": "Dark Green",
        "rebrickable_id": 37,
        "webrick_id": 37,
    },
    (168, 82, 23): {
        "bricklink_id": 36,
        "de": "Dunkelorange",
        "hex": "#a85217",
        "ldraw_id": 36,
        "lego_id": 68,
        "name": "Dark Orange",
        "rebrickable_id": 36,
        "webrick_id": 36,
    },
    (253, 139, 23): {
        "bricklink_id": 10,
        "de": "Orange",
        "hex": "#fd8b17",
        "ldraw_id": 10,
        "lego_id": 4,
        "name": "Orange",
        "rebrickable_id": 10,
        "webrick_id": 4,
    },
    (0, 186, 82): {
        "bricklink_id": 11,
        "de": "Hellgrün",
        "hex": "#00ba52",
        "ldraw_id": 11,
        "lego_id": 37,
        "name": "Bright Green",
        "rebrickable_id": 11,
        "webrick_id": 330,
    },
    (252, 194, 13): {
        "bricklink_id": 106,
        "de": "Hellorange",
        "hex": "#fcc20d",
        "ldraw_id": 106,
        "lego_id": 106,
        "name": "Bright Light Orange",
        "rebrickable_id": 106,
        "webrick_id": 106,
    },
    (255, 236, 108): {
        "bricklink_id": 110,
        "de": "Hellgelb",
        "hex": "#ffec6c",
        "ldraw_id": 110,
        "lego_id": 24,
        "name": "Bright Light Yellow",
        "rebrickable_id": 110,
        "webrick_id": 103,
    },
    (222, 87, 147): {
        "bricklink_id": 23,
        "de": "Helles Pink",
        "hex": "#de5793",
        "ldraw_id": 23,
        "lego_id": 57,
        "name": "Bright Pink",
        "rebrickable_id": 23,
        "webrick_id": 221,
    },
    (222, 121, 162): {
        "bricklink_id": 9,
        "de": "Dunkelpink",
        "hex": "#de79a2",
        "ldraw_id": 9,
        "lego_id": 47,
        "name": "Dark Pink",
        "rebrickable_id": 9,
        "webrick_id": 222,
    },
    (191, 154, 204): {
        "bricklink_id": 21,
        "de": "Lavendel",
        "hex": "#bf9acc",
        "ldraw_id": 21,
        "lego_id": 41,
        "name": "Lavender",
        "rebrickable_id": 21,
        "webrick_id": 351,
    },
    (67, 29, 84): {
        "bricklink_id": 81,
        "de": "Dunkellila",
        "hex": "#431d54",
        "ldraw_id": 81,
        "lego_id": 39,
        "name": "Dark Purple",
        "rebrickable_id": 81,
        "webrick_id": 324,
    },
    (141, 114, 196): {
        "bricklink_id": 373,
        "de": "Mittlerer Lavendel",
        "hex": "#8d72c4",
        "ldraw_id": 373,
        "lego_id": 73,
        "name": "Medium Lavender",
        "rebrickable_id": 373,
        "webrick_id": 196,
    },
    (165, 202, 64): {
        "bricklink_id": 34,
        "de": "Limegrün",
        "hex": "#a5ca40",
        "ldraw_id": 34,
        "lego_id": 34,
        "name": "Lime",
        "rebrickable_id": 34,
        "webrick_id": 34,
    },
    (18, 124, 188): {
        "bricklink_id": 43,
        "de": "Dunkel-Azur",
        "hex": "#127cbc",
        "ldraw_id": 43,
        "lego_id": 105,
        "name": "Dark Azure",
        "rebrickable_id": 43,
        "webrick_id": 322,
    },
    (83, 186, 233): {
        "bricklink_id": 44,
        "de": "Mittel-Azur",
        "hex": "#53bae9",
        "ldraw_id": 44,
        "lego_id": 107,
        "name": "Medium Azure",
        "rebrickable_id": 44,
        "webrick_id": 321,
    },
    (204, 233, 225): {
        "bricklink_id": 39,
        "de": "Helles Aqua",
        "hex": "#cce9e1",
        "ldraw_id": 39,
        "lego_id": 40,
        "name": "Light Aqua",
        "rebrickable_id": 39,
        "webrick_id": 152,
    },
    (54, 30, 13): {
        "bricklink_id": 8,
        "de": "Dunkelbraun",
        "hex": "#361e0d",
        "ldraw_id": 8,
        "lego_id": 86,
        "name": "Dark Brown",
        "rebrickable_id": 8,
        "webrick_id": 308,
    },
    (160, 165, 169): {
        "bricklink_id": 72,
        "de": "Dunkelgrau",
        "hex": "#a0a5a9",
        "ldraw_id": 72,
        "lego_id": 89,
        "name": "Dark Bluish Gray",
        "rebrickable_id": 72,
        "webrick_id": 199,
    },
    (103, 111, 118): {
        "bricklink_id": 71,
        "de": "Hellgrau",
        "hex": "#676f76",
        "ldraw_id": 71,
        "lego_id": 87,
        "name": "Light Bluish Gray",
        "rebrickable_id": 71,
        "webrick_id": 194,
    },
    (89, 93, 96): {
        "bricklink_id": 27,
        "de": "Dunkelgrau (alt)",
        "hex": "#595d60",
        "ldraw_id": 27,
        "lego_id": 20,
        "name": "Dark Gray",
        "rebrickable_id": 27,
        "webrick_id": 27,
    },
    (169, 170, 166): {
        "bricklink_id": 7,
        "de": "Hellgrau (alt)",
        "hex": "#a9aaa6",
        "ldraw_id": 7,
        "lego_id": 19,
        "name": "Light Gray",
        "rebrickable_id": 7,
        "webrick_id": 2,
    },
    (149, 156, 121): {
        "bricklink_id": 151,
        "de": "Olivgrün",
        "hex": "#959c79",
        "ldraw_id": 151,
        "lego_id": 58,
        "name": "Olive Green",
        "rebrickable_id": 151,
        "webrick_id": 154,
    },
    (245, 212, 142): {
        "bricklink_id": 2,
        "de": "Light Nougat / Hell-Beige",
        "hex": "#f5d48e",
        "ldraw_id": 2,
        "lego_id": 2,
        "name": "Light Nougat",
        "rebrickable_id": 2,
        "webrick_id": 226,
    },
}
