"""WeBrick Solid Color palette.

Ausschließlich normale Vollfarben (Solid Color).
Keine transparenten, metallischen oder Unique/Special-Farben.

Quelle: WeBrick Color Chart / Solid Color filter.
https://www.webrick.com/color-chart
"""

WEBRICK_SOLID_PALETTE = {
    # Ursprünglich vorhandene Farben
    (27, 42, 52): {
        "webrick_id": 26,
        "ldraw_id": 0,
        "lego_id": 11,
        "rebrickable_id": 26,
        "bricklink_id": 0,
        "name": "Black",
        "de": "Schwarz",
    },
    (242, 243, 242): {
        "webrick_id": 1,
        "ldraw_id": 15,
        "lego_id": 1,
        "rebrickable_id": 15,
        "bricklink_id": 15,
        "name": "White",
        "de": "Weiß",
    },
    (180, 0, 29): {
        "webrick_id": 21,
        "ldraw_id": 4,
        "lego_id": 5,
        "rebrickable_id": 4,
        "bricklink_id": 4,
        "name": "Red",
        "de": "Rot",
    },
    (144, 31, 118): {
        "webrick_id": 124,
        "ldraw_id": 26,
        "lego_id": 71,
        "rebrickable_id": 26,
        "bricklink_id": 26,
        "name": "Magenta",
        "de": "Magenta",
    },
    (245, 205, 47): {
        "webrick_id": 24,
        "ldraw_id": 14,
        "lego_id": 3,
        "rebrickable_id": 14,
        "bricklink_id": 14,
        "name": "Yellow",
        "de": "Gelb",
    },
    (0, 156, 68): {
        "webrick_id": 28,
        "ldraw_id": 2,
        "lego_id": 6,
        "rebrickable_id": 2,
        "bricklink_id": 2,
        "name": "Green",
        "de": "Grün",
    },
    (0, 76, 146): {
        "webrick_id": 23,
        "ldraw_id": 1,
        "lego_id": 7,
        "rebrickable_id": 1,
        "bricklink_id": 1,
        "name": "Blue",
        "de": "Blau",
    },
    (13, 105, 171): {
        "webrick_id": 102,
        "ldraw_id": 73,
        "lego_id": 42,
        "rebrickable_id": 73,
        "bricklink_id": 73,
        "name": "Medium Blue",
        "de": "Mittelblau",
    },
    (112, 121, 101): {
        "webrick_id": 151,
        "ldraw_id": 378,
        "lego_id": 48,
        "rebrickable_id": 378,
        "bricklink_id": 378,
        "name": "Sand Green",
        "de": "Sandgrün",
    },
    (132, 124, 111): {
        "webrick_id": 135,
        "ldraw_id": 379,
        "lego_id": 55,
        "rebrickable_id": 379,
        "bricklink_id": 379,
        "name": "Sand Blue",
        "de": "Sandblau",
    },
    (95, 49, 9): {
        "webrick_id": 192,
        "ldraw_id": 70,
        "lego_id": 88,
        "rebrickable_id": 70,
        "bricklink_id": 70,
        "name": "Reddish Brown",
        "de": "Rotbraun",
    },
    (221, 196, 150): {
        "webrick_id": 5,
        "ldraw_id": 19,
        "lego_id": 2,
        "rebrickable_id": 19,
        "bricklink_id": 19,
        "name": "Tan",
        "de": "Tan / Beige",
    },
    (178, 117, 89): {
        "webrick_id": 138,
        "ldraw_id": 28,
        "lego_id": 69,
        "rebrickable_id": 28,
        "bricklink_id": 28,
        "name": "Dark Tan",
        "de": "Dunkelbeige",
    },
    (246, 173, 151): {
        "webrick_id": 283,
        "ldraw_id": 78,
        "lego_id": 90,
        "rebrickable_id": 78,
        "bricklink_id": 78,
        "name": "Light Flesh",
        "de": "Heller Hautton",
    },
    (204, 112, 42): {
        "webrick_id": 312,
        "ldraw_id": 84,
        "lego_id": 150,
        "rebrickable_id": 84,
        "bricklink_id": 84,
        "name": "Medium Dark Flesh",
        "de": "Medium Dark Flesh / Medium Nougat",
    },
    # Neu hinzugefügte Farben (Erweiterung auf 39)
    (110, 22, 25): {
        "webrick_id": 320,
        "ldraw_id": 25,
        "lego_id": 85,
        "rebrickable_id": 25,
        "bricklink_id": 25,
        "name": "Dark Red",
        "de": "Dunkelrot",
    },
    (16, 33, 65): {
        "webrick_id": 272,
        "ldraw_id": 272,
        "lego_id": 63,
        "rebrickable_id": 272,
        "bricklink_id": 272,
        "name": "Dark Blue",
        "de": "Dunkelblau",
    },
    (0, 78, 41): {
        "webrick_id": 37,
        "ldraw_id": 37,
        "lego_id": 28,
        "rebrickable_id": 37,
        "bricklink_id": 37,
        "name": "Dark Green",
        "de": "Dunkelgrün",
    },
    (168, 82, 23): {
        "webrick_id": 36,
        "ldraw_id": 36,
        "lego_id": 68,
        "rebrickable_id": 36,
        "bricklink_id": 36,
        "name": "Dark Orange",
        "de": "Dunkelorange",
    },
    (253, 139, 23): {
        "webrick_id": 4,
        "ldraw_id": 10,
        "lego_id": 4,
        "rebrickable_id": 10,
        "bricklink_id": 10,
        "name": "Orange",
        "de": "Orange",
    },
    (0, 186, 82): {
        "webrick_id": 330,
        "ldraw_id": 11,
        "lego_id": 37,
        "rebrickable_id": 11,
        "bricklink_id": 11,
        "name": "Bright Green",
        "de": "Hellgrün",
    },
    (252, 194, 13): {
        "webrick_id": 106,
        "ldraw_id": 106,
        "lego_id": 106,
        "rebrickable_id": 106,
        "bricklink_id": 106,
        "name": "Bright Light Orange",
        "de": "Hellorange",
    },
    (255, 236, 108): {
        "webrick_id": 103,
        "ldraw_id": 110,
        "lego_id": 24,
        "rebrickable_id": 110,
        "bricklink_id": 110,
        "name": "Bright Light Yellow",
        "de": "Hellgelb",
    },
    (222, 87, 147): {
        "webrick_id": 221,
        "ldraw_id": 23,
        "lego_id": 57,
        "rebrickable_id": 23,
        "bricklink_id": 23,
        "name": "Bright Pink",
        "de": "Helles Pink",
    },
    (222, 121, 162): {
        "webrick_id": 222,
        "ldraw_id": 9,
        "lego_id": 47,
        "rebrickable_id": 9,
        "bricklink_id": 9,
        "name": "Dark Pink",
        "de": "Dunkelpink",
    },
    (191, 154, 204): {
        "webrick_id": 351,
        "ldraw_id": 21,
        "lego_id": 41,
        "rebrickable_id": 21,
        "bricklink_id": 21,
        "name": "Lavender",
        "de": "Lavendel",
    },
    (67, 29, 84): {
        "webrick_id": 324,
        "ldraw_id": 81,
        "lego_id": 39,
        "rebrickable_id": 81,
        "bricklink_id": 81,
        "name": "Dark Purple",
        "de": "Dunkellila",
    },
    (141, 114, 196): {
        "webrick_id": 196,
        "ldraw_id": 373,
        "lego_id": 73,
        "rebrickable_id": 373,
        "bricklink_id": 373,
        "name": "Medium Lavender",
        "de": "Mittlerer Lavendel",
    },
    (165, 202, 64): {
        "webrick_id": 34,
        "ldraw_id": 34,
        "lego_id": 34,
        "rebrickable_id": 34,
        "bricklink_id": 34,
        "name": "Lime",
        "de": "Limegrün",
    },
    (18, 124, 188): {
        "webrick_id": 322,
        "ldraw_id": 43,
        "lego_id": 105,
        "rebrickable_id": 43,
        "bricklink_id": 43,
        "name": "Dark Azure",
        "de": "Dunkel-Azur",
    },
    (83, 186, 233): {
        "webrick_id": 321,
        "ldraw_id": 44,
        "lego_id": 107,
        "rebrickable_id": 44,
        "bricklink_id": 44,
        "name": "Medium Azure",
        "de": "Mittel-Azur",
    },
    (204, 233, 225): {
        "webrick_id": 152,
        "ldraw_id": 39,
        "lego_id": 40,
        "rebrickable_id": 39,
        "bricklink_id": 39,
        "name": "Light Aqua",
        "de": "Helles Aqua",
    },
    (54, 30, 13): {
        "webrick_id": 308,
        "ldraw_id": 8,
        "lego_id": 86,
        "rebrickable_id": 8,
        "bricklink_id": 8,
        "name": "Dark Brown",
        "de": "Dunkelbraun",
    },
    (160, 165, 169): {
        "webrick_id": 199,
        "ldraw_id": 72,
        "lego_id": 89,
        "rebrickable_id": 72,
        "bricklink_id": 72,
        "name": "Dark Bluish Gray",
        "de": "Dunkelgrau",
    },
    (103, 111, 118): {
        "webrick_id": 194,
        "ldraw_id": 71,
        "lego_id": 87,
        "rebrickable_id": 71,
        "bricklink_id": 71,
        "name": "Light Bluish Gray",
        "de": "Hellgrau",
    },
    (89, 93, 96): {
        "webrick_id": 27,
        "ldraw_id": 27,
        "lego_id": 20,
        "rebrickable_id": 27,
        "bricklink_id": 27,
        "name": "Dark Gray",
        "de": "Dunkelgrau (alt)",
    },
    (169, 170, 166): {
        "webrick_id": 2,
        "ldraw_id": 7,
        "lego_id": 19,
        "rebrickable_id": 7,
        "bricklink_id": 7,
        "name": "Light Gray",
        "de": "Hellgrau (alt)",
    },
    (149, 156, 121): {
        "webrick_id": 154,
        "ldraw_id": 151,
        "lego_id": 58,
        "rebrickable_id": 151,
        "bricklink_id": 151,
        "name": "Olive Green",
        "de": "Olivgrün",
    },
    (245, 212, 142): {
        "webrick_id": 226,
        "ldraw_id": 2,
        "lego_id": 2,
        "rebrickable_id": 2,
        "bricklink_id": 2,
        "name": "Light Nougat",
        "de": "Light Nougat / Hell-Beige",
    },
}

WEBRICK_SOLID_COLOR_COUNT = len(WEBRICK_SOLID_PALETTE)
